apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-cssre-mkafka-project
rules:
# SRE can get, list, and watch all resources
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# SRE can use oc debug
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  verbs:
  - create
# SRE can delete pods
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - deletecollection
# SRE can delete replicasets
- apiGroups:
  - ""
  resources:
  - replicasets
  verbs:
  - delete
  - deletecollection
